@startuml
портье -> (Просмотреть доступные номера)
клиент -> (Просмотреть доступные номера)
портье -> (Оформить бронирование)
портье -> (Отменить бронирование)
портье -> (Добавить номер)
портье -> (Редактировать номер)
портье -> (Удалить номер)
клиент -> (Просмотреть доступные номер)
клиент -> (Забронировать номер)
@enduml