@startuml
start
:Портье вводит данные номера;
:Проверка уникальности номера комнаты;
if (Номер уникален?) then (Да)
  :Добавить номер в базу данных;
  :Подтвердить добавление;
else (Нет)
  :Вывести сообщение об ошибке;
endif
stop
@enduml