@startuml
start
:Получен запрос на бронирование;
:Подключение к базе данных;
:Поиск доступных номеров;
if (Номера найдены?) then (Да)
  :Создание записи бронирования;
  :Сохранение бронирования в Базе;
  :Обновление статуса номера -> "Забронирован";
  :Возврат подтверждения пользователю;
else (Нет)
  :Формирование сообщения "Нет доступных номеров";
  :Отправка отказа пользователю;
endif
stop
@enduml