@startuml
entity "Room" as Room {
id: INTEGER <<PK>>
room_number: TEXT
price_per_day : REAL
status: TEXT
}
entity "Client" as Client {
id: INTEGER <<PK>>
name: TEXT
phone: TEXT
email: TEXT
}
entity "Booking" as Booking {
id: INTEGER <<PK>>
start_date: DATE
end_date: DATE
room_id: INTEGER <<FK>>
client_id: INTEGER <<FK>>
}
Room||--o{Booking:"1:N"
Client||--o{Booking:"1:N"
@enduml
