@startuml
package "система" {
usecase "Просмотреть доступные номера"
usecase "Оформить бронирование"
usecase "Отменить бронирование"
usecase "Добавить номер"
usecase "Редактировать номер"
usecase "Удалить номер"
usecase "Забронировать номер"
}
портье -> (Просмотреть доступные номера)
клиент -> (Просмотреть доступные номера)
портье -> (Оформить бронирование)
портье -> (Отменить бронирование)
портье -> (Добавить номер)
портье -> (Редактировать номер)
портье -> (Удалить номер)
клиент -> (Забронировать номер)
@enduml